name: 'Convert routes into nginx config'
description: 'A GitHub Action that converts routes into nginx config'
inputs:
  routes_file_pattern:
    description: Where the routes live
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r "${{ github.action_path }}/requirements.txt"
      shell: bash
    - name: Use template to generate nginx config
      id: convert-routes
      run: python "${{ github.action_path }}/convert.py"
      shell: bash
